// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUX7mO-C0vr74LL1Ikql2rsxWMFcdIXME',
    appId: '1:324646185920:web:e60399502ab4f64008b625',
    messagingSenderId: '324646185920',
    projectId: 'ceylogix-df065',
    authDomain: 'ceylogix-df065.firebaseapp.com',
    storageBucket: 'ceylogix-df065.firebasestorage.app',
    measurementId: 'G-BE6G10WBBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxAOhKav-NmOQeMfZh89xy4NmKXQCfM0g',
    appId: '1:324646185920:android:f37297d4a7124bb308b625',
    messagingSenderId: '324646185920',
    projectId: 'ceylogix-df065',
    storageBucket: 'ceylogix-df065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKICvaNbvBf__fZmfqrSJRDucKkNX7gFY',
    appId: '1:324646185920:ios:d9d1adf973fbc3e508b625',
    messagingSenderId: '324646185920',
    projectId: 'ceylogix-df065',
    storageBucket: 'ceylogix-df065.firebasestorage.app',
    iosBundleId: 'com.example.caytrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKICvaNbvBf__fZmfqrSJRDucKkNX7gFY',
    appId: '1:324646185920:ios:d9d1adf973fbc3e508b625',
    messagingSenderId: '324646185920',
    projectId: 'ceylogix-df065',
    storageBucket: 'ceylogix-df065.firebasestorage.app',
    iosBundleId: 'com.example.caytrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUX7mO-C0vr74LL1Ikql2rsxWMFcdIXME',
    appId: '1:324646185920:web:3b37b0d1f280e86808b625',
    messagingSenderId: '324646185920',
    projectId: 'ceylogix-df065',
    authDomain: 'ceylogix-df065.firebaseapp.com',
    storageBucket: 'ceylogix-df065.firebasestorage.app',
    measurementId: 'G-8SPFHKMN66',
  );
}
