import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Core Firebase package
import 'Auth/startup_page.dart'; // Import the dedicated start page
import 'firebase_options.dart'; // Import the file generated by flutterfire configure
import 'dart:ui' as ui;      // for platformViewRegistry
import 'dart:typed_data';    // for UnmodifiableUint8ListView


// --- AppColors definition merged from lib/app_colors.dart ---
class AppColors {
 // Background color requested previously (EEEBFF)
 static const Color background = Color(0xFFEEEBFF);
 // Dark text color (matching the dark blue/gray from the image)
 static const Color darkText = Color(0xFF2C2A3A);
 // Primary button color (2764E7)
 static const Color primaryBlue = Color(0xFF2764E7);
 // Button Gradient colors (using primary blue as the base)
 static const Color buttonGradientStart = Color(0xFF2764E7);
 static const Color buttonGradientEnd = Color(0xFF457AED); 
 // Custom color for the logo/icon based on the new "Antibiotics" theme
 static const Color secondaryColor = Color(0xFF1B998B); 
 // White card background
 static const Color cardBackground = Colors.white;
}
// --- End of AppColors definition ---

// 1. Made main function asynchronous
void main() async {
  // 2. Ensure Flutter binding is initialized
  WidgetsFlutterBinding.ensureInitialized();
  
  // 3. Initialize Firebase using the generated configuration
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print("Firebase initialized successfully!");
  } catch (e) {
    // Basic error reporting if initialization fails
    print("Error initializing Firebase: $e");
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
 const MyApp({super.key});

 @override
 Widget build(BuildContext context) {
  // This widget is the root of your application.
  return MaterialApp(
   title: 'AMS App', // Updated title
   debugShowCheckedModeBanner: false,
   theme: ThemeData(
    // Set a theme based on the primary blue color using the merged constant
    colorScheme: ColorScheme.fromSeed(seedColor: AppColors.primaryBlue), 
    fontFamily: 'Inter',
    useMaterial3: true,
   ),
   // Set the home property to your custom StartPage
   home: const StartPage(),
  );
 }
}